name: learn_torah
description: Learn Torah

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+310

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.3.2
  localstorage: ^4.0.0+1
 

dev_dependencies:
  flutter_test:
   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/html/
   - assets/html/AhareiMot/
   - assets/html/Balak/
   - assets/html/Bamidbar/
   - assets/html/Behaaloteha/
   - assets/html/Behar/
   - assets/html/Behoukotay/
   - assets/html/Bereshit/
   - assets/html/Beshalah/
   - assets/html/Bo/
   - assets/html/css/
   - assets/html/Devarim/
   - assets/html/Ekev/
   - assets/html/Emor/
   - assets/html/Haazinu/
   - assets/html/HayeSara/
   - assets/html/Hukat/
   - assets/html/js/
   - assets/html/Kedoshim/
   - assets/html/KiTavo/
   - assets/html/KiTissa/
   - assets/html/KiTztze/
   - assets/html/Korah/
   - assets/html/LehLeha/
   - assets/html/Massey/
   - assets/html/Matot/
   - assets/html/Mezora/
   - assets/html/Miketz/
   - assets/html/Mishpatim/
   - assets/html/Nasso/
   - assets/html/Nizavim/
   - assets/html/Noah/
   - assets/html/Pekoudey/
   - assets/html/Pinhas/
   - assets/html/Reeh/
   - assets/html/ShelahLeha/
   - assets/html/Shemini/
   - assets/html/Shemot/
   - assets/html/Shoftim/
   - assets/html/Tazria/
   - assets/html/Terouma/
   - assets/html/Tetzave/
   - assets/html/Toldot/
   - assets/html/Vaera/
   - assets/html/Vaethanan/
   - assets/html/Vayakhel/
   - assets/html/Vayehi/
   - assets/html/Vayeleh/
   - assets/html/Vayera/
   - assets/html/Vayeshev/
   - assets/html/Vayetze/
   - assets/html/Vayigash/
   - assets/html/Vayikra/
   - assets/html/Vayishlah/
   - assets/html/VezotHaberaha/
   - assets/html/Yitro/
   - assets/html/Zav/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #    fonts:
  #      - asset: fonts/Schyler-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  #   - family: Trajan Pro
  #    fonts:
  #      - asset: fonts/TrajanPro.ttf
  #      - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
